service: typescriptmongostarter

provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: ap-southeast-1

functions:
    hello:
        handler: src/controllers/user.create
        timeout: 60 # seconds
        memorySize: 128 # mb
